### ISSUE TITLE
custom message error  -  "zbar_ros/Marker.h: No such file or directory"

### ISSUE THREAD

**Issue by amamory** [vicoslab/vicos_ros#1]
Hi, 

I was trying to compile this code but I got the following error
"catkin_ws/src/vicos_ros-master/zbar_ros/src/main.cpp:13:29: fatal error: zbar_ros/Marker.h: No such file or directory"
I know it is related to the custom message generation. I modified the package.xml to include 'genmsg' but it wont work either.

could you give me some hints on how to compile this package ?

best regards,
Alexandre

**Comment by lukacu** [comment]
Thank you for the fix, I think it works.
